# Generated by Django 3.2.4 on 2021-06-22 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='camera',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
